# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oauth2ProviderAccesstoken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('expires', models.DateTimeField()),
                ('scope', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'oauth2_provider_accesstoken',
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('expires', models.DateTimeField()),
                ('redirect_uri', models.CharField(max_length=255)),
                ('scope', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'oauth2_provider_grant',
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderRefreshtoken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'oauth2_provider_refreshtoken',
            },
        ),
        migrations.CreateModel(
            name='SocialAuthCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=75)),
                ('code', models.CharField(max_length=32)),
                ('verified', models.BooleanField()),
            ],
            options={
                'db_table': 'social_auth_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SsoOauth2Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100, unique=True)),
                ('redirect_uris', models.TextField()),
                ('client_type', models.CharField(max_length=32)),
                ('authorization_grant_type', models.CharField(max_length=32)),
                ('client_secret', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('is_internal', models.BooleanField()),
            ],
            options={
                'managed': False,
                'db_table': 'sso_oauth2application',
            },
        ),
        migrations.CreateModel(
            name='YouckanUserprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'youckan_userprofile',
            },
        ),
        migrations.CreateModel(
            name='YouckanUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField()),
                ('is_superuser', models.BooleanField()),
                ('email', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('slug', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'youckan_user',
            },
        ),
    ]
